# 服务器基础配置(Basic server configuration)
server:
  # 服务器监听地址和端口(Server listening address and port)
  ip: 0.0.0.0
  port: 8000
  token: "你的token"  # 服务器访问令牌
  # 认证配置
  auth:
    # 是否启用认证
    enabled: false
    # 允许的设备ID列表
    allowed_devices: []
    # 有效的token列表
    tokens: []

# 数据库配置
database:
  # 数据库类型：mysql, postgresql, sqlite
  type: mysql
  
  # MySQL配置
  host: localhost
  port: 3306
  user: root
  password: ""
  name: ai_server_go
  charset: utf8mb4
  parse_time: true
  loc: Local
  
  # PostgreSQL特定配置（当type为postgresql时使用）
  # ssl_mode: disable  # disable, require, verify-ca, verify-full
  
  # SQLite特定配置（当type为sqlite时使用）
  # file_path: ./data/ai_server.db
  
  # 连接池配置
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600s

# Web界面配置
web:
  # 是否启用Web界面
  enabled: true
  # Web服务监听端口
  port: 8080
  # 由ota下发的WebSocket地址
  websocket: ws://你的ip:8000
  vision: http://你的ip:8080/api/vision

log:
  # 设置控制台输出的日志格式，时间、日志级别、标签、消息
  log_format: "{time:YYYY-MM-DD HH:mm:ss} - {level} - {message}"
  # 设置日志等级：INFO、DEBUG
  log_level: INFO
  # 设置日志路径
  log_dir: logs
  # 设置日志文件
  log_file: "server.log"

# 注意：ASR、TTS、LLM、VLLLM配置已迁移到数据库
# 请通过API接口管理这些配置：
# - GET /api/system-configs/provider - 获取所有provider配置
# - POST /api/system-configs/provider - 创建provider配置
# - PUT /api/system-configs/provider/{category}/{name} - 更新provider配置
# - DELETE /api/system-configs/provider/{category}/{name} - 删除provider配置

# 数据库配置示例：
# 
# MySQL配置示例：
# database:
#   type: mysql
#   host: localhost
#   port: 3306
#   user: root
#   password: "your_password"
#   name: ai_server_go
#   charset: utf8mb4
#   parse_time: true
#   loc: Local
#   max_open_conns: 100
#   max_idle_conns: 10
#   conn_max_lifetime: 3600s
#
# PostgreSQL配置示例：
# database:
#   type: postgresql
#   host: localhost
#   port: 5432
#   user: postgres
#   password: "your_password"
#   name: ai_server_go
#   ssl_mode: disable
#   max_open_conns: 100
#   max_idle_conns: 10
#   conn_max_lifetime: 3600s
#
# SQLite配置示例：
# database:
#   type: sqlite
#   name: ./data/ai_server.db
#   file_path: ./data/ai_server.db
#   max_open_conns: 1
#   max_idle_conns: 1
#   conn_max_lifetime: 3600s
